# 创建和保持Numpy ndarray

首先是导入numpy的模块,一般都会取别名np

In [29]:
import numpy as np

In [30]:
x = np.array([1,2,3,4,5])

In [31]:
print(x.dtype)


int64


In [32]:
print(x.shape)


(5,)


In [33]:
print(type(x))

<type 'numpy.ndarray'>


In [34]:
x = np.array(['hello','world'])

In [35]:
print(x.dtype)

|S5


In [36]:
x = np.array(['Hello','World'])

In [37]:
print(x.dtype)

|S5


可以看出，虽然 Python 列表具有不同的数据类型，但是 x 中的元素类型都一样，即具有 21 个字符的 Unicode 字符串。在 NumPy 简介的剩余部分，我们将不使用存储字符串的 ndarray，但是请注意，ndarray 也可以存储字符串。

现在看看如何利用嵌套 Python 列表创建秩为 2 的 ndarray。

In [38]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [39]:
print(type(Y))
print(Y.shape)
print(Y.dtype)

<type 'numpy.ndarray'>
(4, 3)
int64


到目前为止，我们只创建了包含整数和字符串的 ndarray。我们发现，当我们创建只有整数的 ndarray 时，NumPy 将自动为其元素分配 dtype int64。我们来看看当我们创建具有浮点数和整数的 ndarray 时，会发生什么。

In [40]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

In [41]:
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

('The elements in x are of type:', dtype('int64'))
('The elements in y are of type:', dtype('float64'))
('The elements in z are of type:', dtype('float64'))


numpy只支持相同类型的数据.up Casting
可以看出，当我们创建只有浮点数的 ndarray 时，NumPy 将元素当做 64 位浮点数 (float64) 存储在内存中。但是，当我们创建同时包含浮点数和整数的 ndarray 时，就像上面的 z ndarray，NumPy 也会为其元素分配 float64 dtype。这叫做向上转型。因为 ndarray 的所有元素都必须类型相同，因此在这种情况下，NumPy 将 z 中的整数向上转型为浮点数，避免在进行数学计算时丢失精度。

虽然 NumPy 自动为 ndarray 选择 dtype，但是 NumPy 也允许你指定要为 ndarray 的元素分配的特定 dtype。当你在 np.array() 函数中创建 ndarray 时，可以使用关键字 dtype 指定 dtype。我们来看一个示例：


In [42]:
x = np.array([1, 2, 3, 4, 5])

In [43]:
np.save("my_array",x)

In [44]:
y = np.load('my_array.npy')
# 这里的文件扩展名必须是npy
print(y)

[1 2 3 4 5]


# 使用内置函数创建ndarray

numpy有很多大家喜闻乐见的快捷方法,比如ones和zeros,分别是创建全是1或者是全是0的ndarray的方法.接受元组作为实参,**元组在作为实参的时候,括号不可以省略.**

In [46]:
x = np.ones(3,4)

TypeError: data type not understood

In [47]:
x = np.ones((3,4))

In [48]:
print(x)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [51]:
print(x.dtype)
print(x.shape)
print(x.size)



float64
(3, 4)
12


默认是float64的类型的,可以通过定义dtype来定义其他的类型

In [53]:
y = np.zeros((3,4),dtype = int)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


full方法则可以填充其他任何数据

In [56]:
z = np.full((5,6),6,dtype = int)
print(z)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


单位矩阵,主对角线是1,其他位置都是0,在grasshopper中随处可见

In [58]:
u = np.eye(4,dtype=int)
print(u)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [59]:
v = np.diag([10,20,30,44])
print(v)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 44]]


arange,产生等差数列,功能类似于grasshopper中的seriesnp.arange(start,stop,step)

In [61]:
w = np.arange(10)
print(w)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
w = np.arange(4,10)
print(w)

[4 5 6 7 8 9]


In [63]:
w = np.arange(4,10,0.5)
print(w)

[ 4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


linspace,产生等差数列,功能类似于grasshopper中的range

In [68]:
w = np.linspace(4,25,7)
print(w)

[  4.    7.5  11.   14.5  18.   21.5  25. ]


In [69]:
w = np.linspace(4,25,7,dtype = int)
print(w)

[ 4  7 11 14 18 21 25]


In [70]:
w = np.linspace(4,25,7,dtype = int,endpoint = False)
print(w)

[ 4  7 10 13 16 19 22]


In [71]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [73]:
y = np.reshape(x,(2,5))
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]


NumPy 的一大特性是某些函数还可以当做方法使用。这样我们便能够在一行代码中按顺序应用不同的函数。ndarray 方法和 ndarray 属性相似，它们都使用点记法 (.)。我们来看看如何只用一行代码实现上述示例中的相同结果：

In [75]:
z= np.arange(10).reshape(2,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [76]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

()
('X = \n', array([[  0.,   5.],
       [ 10.,  15.],
       [ 20.,  25.],
       [ 30.,  35.],
       [ 40.,  45.]]))
()
('X has dimensions:', (5, 2))
('X is an object of type:', <type 'numpy.ndarray'>)
('The elements in X are of type:', dtype('float64'))


我们将创建的最后一种 ndarray 是随机 ndarray。随机 ndarray 是包含随机数字的数组。在机器学习中，通常需要创建随机指标，例如，在初始化神经网络的权重时。NumPy 提供了各种随机函数来帮助我们创建任何形状的随机 ndarray。

我们先使用 `np.random.random(shape)` 函数创建具有给定形状的 ndarray，其中包含位于半开区间 [0.0, 1.0) 内的随机浮点数。

In [79]:
x = np.random.random((4,5))
print(x)

[[ 0.40373318  0.44207639  0.21916446  0.9621676   0.79259868]
 [ 0.26119017  0.14766081  0.53743206  0.40044941  0.17527799]
 [ 0.48231058  0.63469459  0.893235    0.0879879   0.684408  ]
 [ 0.89526191  0.76776554  0.07016785  0.59108722  0.45647168]]


In [80]:
x = np.random.randint(4,16,size=(3,4))
print(x)

[[11  6 13 13]
 [ 9 15  4 14]
 [ 5 15 10  7]]


In [82]:
x = np.random.normal(50,30,size=(30,))
print(x)

[  67.73683106   29.21071819  -15.48954302  101.17933789   50.33788665
   11.42784413    9.8740634     6.39672262   64.0710813    28.17372349
   61.78766896   82.86369054  -19.89692023  103.70435987   26.31193052
   25.28609327   31.66273123   56.20844386   44.43285155   70.78080613
   18.75436973   20.5118558    70.52608297   62.96479567   28.45260684
   90.91928916   72.42348696   90.4717188    -2.11017819   -4.00194112]
