# 创建和保持Numpy ndarray

首先是导入numpy的模块,一般都会取别名np

In [1]:
import numpy as np

In [4]:
groceries[[2:3x = np.array([1,2,3,4,5])

In [5]:
print(x.dtype)


int64


In [6]:
print(x.shape)


(5,)


In [7]:
print(type(x))

<type 'numpy.ndarray'>


In [8]:
x = np.array(['hello','world'])

In [9]:
print(x.dtype)

|S5


In [10]:
x = np.array(['Hello','World'])

In [11]:
print(x.dtype)

|S5


可以看出，虽然 Python 列表具有不同的数据类型，但是 x 中的元素类型都一样，即具有 21 个字符的 Unicode 字符串。在 NumPy 简介的剩余部分，我们将不使用存储字符串的 ndarray，但是请注意，ndarray 也可以存储字符串。

现在看看如何利用嵌套 Python 列表创建秩为 2 的 ndarray。

In [12]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

In [13]:
print(type(Y))
print(Y.shape)
print(Y.dtype)

<type 'numpy.ndarray'>
(4, 3)
int64


到目前为止，我们只创建了包含整数和字符串的 ndarray。我们发现，当我们创建只有整数的 ndarray 时，NumPy 将自动为其元素分配 dtype int64。我们来看看当我们创建具有浮点数和整数的 ndarray 时，会发生什么。

In [14]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

In [15]:
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

('The elements in x are of type:', dtype('int64'))
('The elements in y are of type:', dtype('float64'))
('The elements in z are of type:', dtype('float64'))


numpy只支持相同类型的数据.up Casting
可以看出，当我们创建只有浮点数的 ndarray 时，NumPy 将元素当做 64 位浮点数 (float64) 存储在内存中。但是，当我们创建同时包含浮点数和整数的 ndarray 时，就像上面的 z ndarray，NumPy 也会为其元素分配 float64 dtype。这叫做向上转型。因为 ndarray 的所有元素都必须类型相同，因此在这种情况下，NumPy 将 z 中的整数向上转型为浮点数，避免在进行数学计算时丢失精度。

虽然 NumPy 自动为 ndarray 选择 dtype，但是 NumPy 也允许你指定要为 ndarray 的元素分配的特定 dtype。当你在 np.array() 函数中创建 ndarray 时，可以使用关键字 dtype 指定 dtype。我们来看一个示例：


In [16]:
x = np.array([1, 2, 3, 4, 5])

In [17]:
np.save("my_array",x)

In [18]:
y = np.load('my_array.npy')
# 这里的文件扩展名必须是npy
print(y)

[1 2 3 4 5]


# 使用内置函数创建ndarray

numpy有很多大家喜闻乐见的快捷方法,比如ones和zeros,分别是创建全是1或者是全是0的ndarray的方法.接受元组作为实参,**元组在作为实参的时候,括号不可以省略.**

## np.ones

In [19]:
x = np.ones(3,4)

TypeError: data type not understood

In [20]:
x = np.ones((3,4))

In [21]:
print(x)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [22]:
print(x.dtype)
print(x.shape)
print(x.size)



float64
(3, 4)
12


默认是float64的类型的,可以通过定义dtype来定义其他的类型

In [23]:
y = np.zeros((3,4),dtype = int)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


full方法则可以填充其他任何数据

In [24]:
z = np.full((5,6),6,dtype = int)
print(z)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


单位矩阵,主对角线是1,其他位置都是0,在grasshopper中随处可见

In [25]:
u = np.eye(4,dtype=int)
print(u)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [26]:
v = np.diag([10,20,30,44])
print(v)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 44]]


arange,产生等差数列,功能类似于grasshopper中的seriesnp.arange(start,stop,step)

In [27]:
w = np.arange(10)
print(w)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
w = np.arange(4,10)
print(w)

[4 5 6 7 8 9]


In [29]:
w = np.arange(4,10,0.5)
print(w)

[ 4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


linspace,产生等差数列,功能类似于grasshopper中的range

In [30]:
w = np.linspace(4,25,7)
print(w)

[  4.    7.5  11.   14.5  18.   21.5  25. ]


In [31]:
w = np.linspace(4,25,7,dtype = int)
print(w)

[ 4  7 11 14 18 21 25]


In [32]:
w = np.linspace(4,25,7,dtype = int,endpoint = False)
print(w)

[ 4  7 10 13 16 19 22]


In [33]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
y = np.reshape(x,(2,5))
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]


NumPy 的一大特性是某些函数还可以当做方法使用。这样我们便能够在一行代码中按顺序应用不同的函数。ndarray 方法和 ndarray 属性相似，它们都使用点记法 (.)。我们来看看如何只用一行代码实现上述示例中的相同结果：

In [35]:
z= np.arange(10).reshape(2,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

()
('X = \n', array([[  0.,   5.],
       [ 10.,  15.],
       [ 20.,  25.],
       [ 30.,  35.],
       [ 40.,  45.]]))
()
('X has dimensions:', (5, 2))
('X is an object of type:', <type 'numpy.ndarray'>)
('The elements in X are of type:', dtype('float64'))


## random,randint,normal

我们将创建的最后一种 ndarray 是随机 ndarray。随机 ndarray 是包含随机数字的数组。在机器学习中，通常需要创建随机指标，例如，在初始化神经网络的权重时。NumPy 提供了各种随机函数来帮助我们创建任何形状的随机 ndarray。

我们先使用 `np.random.random(shape)` 函数创建具有给定形状的 ndarray，其中包含位于半开区间 [0.0, 1.0) 内的随机浮点数。

In [37]:
x = np.random.random((4,5))
print(x)

[[ 0.9093335   0.81779246  0.77588044  0.46991505  0.46468689]
 [ 0.61282032  0.80010946  0.52969953  0.88833487  0.72607183]
 [ 0.22937583  0.36077777  0.72956669  0.80920237  0.62465458]
 [ 0.47849554  0.38518722  0.39967904  0.74441897  0.29734238]]


In [38]:
x = np.random.randint(4,16,size=(3,4))
print(x)

[[ 6  9  4 10]
 [ 7 15 11 12]
 [ 7 11  7  9]]


In [39]:
x = np.random.normal(50,30,size=(30,))
print(x)

[  47.96532288   63.5675139    35.19970898   90.03332646   13.8667444
   78.85006572   61.78924721   -7.78033158  111.80284739   39.63024069
   48.55927157   20.30928485   51.29879874   53.37186882   51.24223898
   60.25375386   47.46739674   47.31288215   43.74529566   75.45370184
   24.14069357   53.43078035   36.83903689   59.84184932   62.86901617
   -2.07213843   55.62758788   72.22958083   78.30101748   77.6152018 ]


numpy数组的数据可以被修改,

In [40]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

()
('x = ', array([1, 2, 3, 4, 5]))
()
('This is First Element in x:', 1)
('This is Second Element in x:', 2)
('This is Fifth (Last) Element in x:', 5)
()
('This is First Element in x:', 1)
('This is Second Element in x:', 2)
('This is Fifth (Last) Element in x:', 5)


In [41]:
x[3] = 20


In [42]:
print(x)

[ 1  2  3 20  5]


In [43]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
print(x[0,0],x[0,1],x[2,2])

(1, 2, 9)


In [45]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## delete删除

删除用delete

In [46]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [47]:
y = np.delete(x,[1,2])
print(y)

[1 4 5 6 7 8 9]


In [48]:
y = np.delete(x,[1,-1])
# 负数的index会被忽略掉,报错

print(y)

[1 3 4 5 6 7 8 9]


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: in the future negative indices will not be ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


In [49]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
np.delete(y,[0],axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [51]:
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
np.delete(y,[0,2],axis=1)

array([[2],
       [5],
       [8]])

In [53]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## append追加

In [54]:
z = np.append(y,[[7,7,8]],axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 7 8]]


In [55]:
np.append(z,[[111],[222],[333]],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [56]:
np.append(y,[[7,7,8,9]],axis=0)
# 如果出现个数不相同的情况,则报错

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [57]:
y = np.arange(1,10)
print(y)

[1 2 3 4 5 6 7 8 9]


In [58]:
np.append(y,[1,3,1,1,1,1,11,2,2],axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  3,  1,  1,  1,  1, 11,  2,
        2])

In [59]:
y = np.arange(1,10)
print(y)

[1 2 3 4 5 6 7 8 9]


In [60]:
np.insert(y,3,[444,555])

array([  1,   2,   3, 444, 555,   4,   5,   6,   7,   8,   9])

In [61]:
y = np.array([[1,2,3],[7,8,9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [62]:
np.insert(y,1,[4,5,6],axis=0)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## vstack垂直叠加,hstack水平叠加

In [63]:
 x= np.array([1,2])

In [64]:
y = np.array([[4,5],[6,7]])

In [65]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [4 5]
 [6 7]]


In [66]:
x.reshape(2,1)



array([[1],
       [2]])

In [67]:
print(x)

[1 2]


In [68]:
z = np.hstack((y,x.reshape(2,1)))
print(z)

[[4 5 1]
 [6 7 2]]


# ndarray切片

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]
三种形式结束索引都不包含在内

In [69]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [70]:
x[1:4]

array([2, 3, 4])

In [71]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [72]:
x[1:4,2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [73]:
x[1:4,2:7]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [74]:
x[1:100,2:100]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [75]:
x[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [76]:
x[1:4,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
x[2,:]

array([10, 11, 12, 13, 14])

In [78]:
x[:,2:3]
#这种方式返回的是一个rank为2的ndarray,

array([[ 2],
       [ 7],
       [12],
       [17]])

In [79]:
x[:,2]
#这种方式返回的是一个rank为1的ndarray,

array([ 2,  7, 12, 17])

原始数组 X 的切片没有复制到变量 Z 中。X 和 Z 现在只是同一个 ndarray 的两个不同名称。我们提到，切片只是创建了原始数组的一个视图。也就是说，如果对 Z 做出更改，也会更改 X 中的元素。我们来看一个示例：

In [80]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

# We print X
print()
print('X = \n', X)
print()

()
('X = \n', array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]))
()
()
('Z = \n', array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]]))
()
()
('X = \n', array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 555]]))
()


## copy
copy同时当做函数和方法,可以创建一个和原来的ndarray隔离的新的

In [81]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)

()
('X = \n', array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]))
()
()
('X = \n', array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]))
()
('Z = \n', array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]]))
()
('W = \n', array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 444]]))


### 可以定义一个ndarray来用来切片其他的ndarray

In [82]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [83]:
indices = np.array([1,3])
print(indices)

[1 3]


In [84]:
x[indices,:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [85]:
x[:,indices]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [86]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

np.diag(ndarray,k=n)可以查找位于对角线上的元素

In [87]:
np.diag(x,k=-1)

array([ 5, 11, 17])

In [88]:
np.diag(x,k=2)

array([ 2,  8, 14])

In [89]:
np.diag([111,2222,3333,444])

array([[ 111,    0,    0,    0],
       [   0, 2222,    0,    0],
       [   0,    0, 3333,    0],
       [   0,    0,    0,  444]])

In [90]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])


In [91]:
np.unique(X)

array([1, 2, 3, 5, 8])

## 布尔型索引、集合运算和排序

### 布尔型索引

In [92]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [93]:
X[X>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [94]:
X[(X>10)&(X<=20)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 集合运算

In [95]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

()
('x = ', array([1, 2, 3, 4, 5]))
()
('y = ', array([6, 7, 2, 8, 4]))
()
('The elements that are both in x and y:', array([2, 4]))
('The elements that are in x that are not in y:', array([1, 3, 5]))
('All the elements of x and y:', array([1, 2, 3, 4, 5, 6, 7, 8]))


### 排序
用做方法的时候原来的ndarray改变变,用作函数的时候不变

In [97]:
x = np.random.randint(1,11,size=(10,))
print(x)

[ 9 10  7 10 10  6  5  9 10  9]


In [99]:
print(np.sort(x))
print(x)

[ 5  6  7  9  9  9 10 10 10 10]
[ 9 10  7 10 10  6  5  9 10  9]


In [100]:
print(np.sort(np.unique(x)))

[ 5  6  7  9 10]


In [101]:
x.sort()
print(x)

[ 5  6  7  9  9  9 10 10 10 10]


In [102]:
x = np.random.randint(1,11,size=(5,5))

In [103]:
print(x)

[[ 4  4  6  9 10]
 [ 6  4  3  9  9]
 [ 4  9  4  7  6]
 [ 9  8  2  1  6]
 [ 4 10  1  3  9]]


In [104]:
print(np.sort(x,axis=0))

[[ 4  4  1  1  6]
 [ 4  4  2  3  6]
 [ 4  8  3  7  9]
 [ 6  9  4  9  9]
 [ 9 10  6  9 10]]


In [105]:
print(np.sort(x,axis=1))

[[ 4  4  6  9 10]
 [ 3  4  6  9  9]
 [ 4  4  6  7  9]
 [ 1  2  6  8  9]
 [ 1  3  4  9 10]]


## 算数运算和广播

In [106]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

()
('x = ', array([1, 2, 3, 4]))
()
('y = ', array([ 5.5,  6.5,  7.5,  8.5]))
()
('x + y = ', array([  6.5,   8.5,  10.5,  12.5]))
('add(x,y) = ', array([  6.5,   8.5,  10.5,  12.5]))
()
('x - y = ', array([-4.5, -4.5, -4.5, -4.5]))
('subtract(x,y) = ', array([-4.5, -4.5, -4.5, -4.5]))
()
('x * y = ', array([  5.5,  13. ,  22.5,  34. ]))
('multiply(x,y) = ', array([  5.5,  13. ,  22.5,  34. ]))
()
('x / y = ', array([ 0.18181818,  0.30769231,  0.4       ,  0.47058824]))
('divide(x,y) = ', array([ 0.18181818,  0.30769231,  0.4       ,  0.47058824]))


In [107]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

()
('X = \n', array([[1, 2],
       [3, 4]]))
()
('Y = \n', array([[ 5.5,  6.5],
       [ 7.5,  8.5]]))
()
('X + Y = \n', array([[  6.5,   8.5],
       [ 10.5,  12.5]]))
()
('add(X,Y) = \n', array([[  6.5,   8.5],
       [ 10.5,  12.5]]))
()
('X - Y = \n', array([[-4.5, -4.5],
       [-4.5, -4.5]]))
()
('subtract(X,Y) = \n', array([[-4.5, -4.5],
       [-4.5, -4.5]]))
()
('X * Y = \n', array([[  5.5,  13. ],
       [ 22.5,  34. ]]))
()
('multiply(X,Y) = \n', array([[  5.5,  13. ],
       [ 22.5,  34. ]]))
()
('X / Y = \n', array([[ 0.18181818,  0.30769231],
       [ 0.4       ,  0.47058824]]))
()
('divide(X,Y) = \n', array([[ 0.18181818,  0.30769231],
       [ 0.4       ,  0.47058824]]))


In [108]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2

()
('x = ', array([1, 2, 3, 4]))
()
('EXP(x) =', array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003]))
()
('SQRT(x) =', array([ 1.        ,  1.41421356,  1.73205081,  2.        ]))
()
('POW(x,2) =', array([ 1,  4,  9, 16]))


In [109]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Maximum value of all elements in X:', X.min())
print('Maximum value of all elements in the columns of X:', X.min(axis=0))
print('Maximum value of all elements in the rows of X:', X.min(axis=1))

()
('X = \n', array([[1, 2],
       [3, 4]]))
()
('Average of all elements in X:', 2.5)
('Average of all elements in the columns of X:', array([ 2.,  3.]))
('Average of all elements in the rows of X:', array([ 1.5,  3.5]))
()
('Sum of all elements in X:', 10)
('Sum of all elements in the columns of X:', array([4, 6]))
('Sum of all elements in the rows of X:', array([3, 7]))
()
('Standard Deviation of all elements in X:', 1.1180339887498949)
('Standard Deviation of all elements in the columns of X:', array([ 1.,  1.]))
('Standard Deviation of all elements in the rows of X:', array([ 0.5,  0.5]))
()
('Median of all elements in X:', 2.5)
('Median of all elements in the columns of X:', array([ 2.,  3.]))
('Median of all elements in the rows of X:', array([ 1.5,  3.5]))
()
('Maximum value of all elements in X:', 4)
('Maximum value of all elements in the columns of X:', array([3, 4]))
('Maximum value of all elements in the rows of X:', array([2, 4]))
()
('Maximum value of all elements in X:'

In [110]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

()
('X = \n', array([[1, 2],
       [3, 4]]))
()
('3 * X = \n', array([[ 3,  6],
       [ 9, 12]]))
()
('3 + X = \n', array([[4, 5],
       [6, 7]]))
()
('X - 3 = \n', array([[-2, -1],
       [ 0,  1]]))
()
('X / 3 = \n', array([[0, 0],
       [1, 1]]))


In [111]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)

()
('x = ', array([1, 2, 3]))
()
()
('Y = \n', array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]))
()
()
('Z = \n', array([[1],
       [2],
       [3]]))
()
('x + Y = \n', array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]]))
()
('Z + Y = \n', array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]]))


In [112]:
 x = np.arange(1,10).reshape(3,3)

In [113]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [114]:
x.mean(axis = 0)

array([ 4.,  5.,  6.])

In [2]:
import sys
print(sys.version)

2.7.13+ (default, Jul 19 2017, 18:15:03) 
[GCC 6.4.0 20170704]
